from retrievers import *
import functools

configurations = {
    'config_parent1': {
        'retriever_type': 'parent',
        'embeddings_func': embeddings_1,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'parent_chunk_size': 2000,
        'child_chunk_size': 200,
        'number_of_retrievals': 5,
    },
    'config_parent2': {
        'retriever_type': 'parent',
        'embeddings_func': embeddings_1,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'parent_chunk_size': 1000,
        'child_chunk_size': 250,
        'number_of_retrievals': 7,
    },
    'config_1': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_1,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 1000,
        'chunk_overlap': 200,
        'number_of_retrievals': 5,
        'top_number_of_retrievals': 3,
    },
    'config_2': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_1,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 2000,
        'chunk_overlap': 400,
        'number_of_retrievals': 5,
        'top_number_of_retrievals': 3,
    },
    'config_3': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_1,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 500,
        'chunk_overlap': 50,
        'number_of_retrievals': 5,
        'top_number_of_retrievals': 3,
    },
    'config_4': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_1,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 1000,
        'chunk_overlap': 200,
        'number_of_retrievals': 7,
        'top_number_of_retrievals': 2,
    },
    'config_5': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_1,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 2000,
        'chunk_overlap': 400,
        'number_of_retrievals': 7,
        'top_number_of_retrievals': 2,
    },
    'config_6': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_1,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 500,
        'chunk_overlap': 50,
        'number_of_retrievals': 7,
        'top_number_of_retrievals': 2,
    },
    'config_7': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_1,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 1000,
        'chunk_overlap': 200,
        'number_of_retrievals': 10,
        'top_number_of_retrievals': 4,
    },
    'config_8': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_1,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 2000,
        'chunk_overlap': 400,
        'number_of_retrievals': 10,
        'top_number_of_retrievals': 4,
    },
    'config_9': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_1,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 500,
        'chunk_overlap': 50,
        'number_of_retrievals': 10,
        'top_number_of_retrievals': 4,
    },
    'config_10': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_2,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 1000,
        'chunk_overlap': 200,
        'number_of_retrievals': 5,
        'top_number_of_retrievals': 3,
    },
    'config_11': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_2,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 2000,
        'chunk_overlap': 400,
        'number_of_retrievals': 5,
        'top_number_of_retrievals': 3,
    },
    'config_12': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_2,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 500,
        'chunk_overlap': 50,
        'number_of_retrievals': 5,
        'top_number_of_retrievals': 3,
    },
    'config_13': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_2,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 1000,
        'chunk_overlap': 200,
        'number_of_retrievals': 7,
        'top_number_of_retrievals': 2,
    },
    'config_14': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_2,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 2000,
        'chunk_overlap': 400,
        'number_of_retrievals': 7,
        'top_number_of_retrievals': 2,
    },
    'config_15': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_2,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 500,
        'chunk_overlap': 50,
        'number_of_retrievals': 7,
        'top_number_of_retrievals': 2,
    },
    'config_16': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_2,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 1000,
        'chunk_overlap': 200,
        'number_of_retrievals': 10,
        'top_number_of_retrievals': 4,
    },
    'config_17': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_2,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 2000,
        'chunk_overlap': 400,
        'number_of_retrievals': 10,
        'top_number_of_retrievals': 4,
    },
    'config_18': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_2,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 500,
        'chunk_overlap': 50,
        'number_of_retrievals': 10,
        'top_number_of_retrievals': 4,
    },
    'config_19': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_3,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 1000,
        'chunk_overlap': 200,
        'number_of_retrievals': 5,
        'top_number_of_retrievals': 3,
    },
    'config_20': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_3,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 2000,
        'chunk_overlap': 400,
        'number_of_retrievals': 5,
        'top_number_of_retrievals': 3,
    },
    'config_21': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_3,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 500,
        'chunk_overlap': 50,
        'number_of_retrievals': 5,
        'top_number_of_retrievals': 3,
    },
    'config_22': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_3,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 1000,
        'chunk_overlap': 200,
        'number_of_retrievals': 7,
        'top_number_of_retrievals': 2,
    },
    'config_23': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_3,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 2000,
        'chunk_overlap': 400,
        'number_of_retrievals': 7,
        'top_number_of_retrievals': 2,
    },
    'config_24': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_3,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 500,
        'chunk_overlap': 50,
        'number_of_retrievals': 7,
        'top_number_of_retrievals': 2,
    },
    'config_25': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_3,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 1000,
        'chunk_overlap': 200,
        'number_of_retrievals': 10,
        'top_number_of_retrievals': 4,
    },
    'config_26': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_3,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 2000,
        'chunk_overlap': 400,
        'number_of_retrievals': 10,
        'top_number_of_retrievals': 4,
    },
    'config_27': {
        'retriever_type': 'rerank',
        'embeddings_func': embeddings_3,
        'vectorstore_func': partial(vectorstore_1, index_name="l2"),
        'rerank_func': rerank_1,
        'chunk_size': 500,
        'chunk_overlap': 50,
        'number_of_retrievals': 10,
        'top_number_of_retrievals': 4,
    },
}

def process_configuration(config, documents):
    if config['retriever_type'] == 'rerank':
        retriever = retriever_rerank(
            documents,
            config['embeddings_func'],
            config['vectorstore_func'],
            config['rerank_func'],
            chunk_size=config['chunk_size'],
            chunk_overlap=config['chunk_overlap'],
            number_of_retrievals=config['number_of_retrievals'],
            top_number_of_retrievals=config['top_number_of_retrievals'],
        )
    elif config['retriever_type'] == 'parent':
        retriever = retriever_parent(
            documents,
            config['embeddings_func'],
            config['vectorstore_func'],
            parent_chunk_size=config['parent_chunk_size'],
            child_chunk_size=config['child_chunk_size'],
            number_of_retrievals=config['number_of_retrievals'],
        )

    return retriever

def convert_functions_to_names(config):
    new_config = config.copy()

    for key, value in config.items():
        if callable(value):
            if isinstance(value, functools.partial):
                # If it's a partial function, get the original function's name
                new_config[key] = value.func.__name__
            else:
                # If it's a regular function, get its name
                new_config[key] = value.__name__

    return new_config